import github from '@actions/github'

export default function (data) {
  // extract relevant variables
  const { diff: { summary, patches }, textContent, customHeader, showHeader, showFooter } = data
  const { runId, repo, sha } = github.context
  /* c8 ignore next 4 */
  const headerText = customHeader || ':robot: *Terraform Report*'

  data.header = showHeader
    ? `
### ${headerText}
---`
    : ''
  
  data.footer = showFooter 
    ? `
---
> This comment was generated by [Terraform Pull Request Report Generator](https://github.com/ahmadnassri/action-terraform-report) - action run [\`#${runId}\`](https://github.com/${repo.owner}/${repo.repo}/actions/runs/${runId}) - commit ${sha}
`
    : ''

  data.body = `${header}
##### Plan: \`${summary.create}\` to add, \`${summary.update}\` to change, \`${summary.delete}\` to destroy
`

  if (data.showPlan === 'true') {
    data.body += `
<details><summary>Show Plan</summary>

\`\`\`terraform
${textContent}
\`\`\`
</details>
${data.footer}`
  }

  if (data.showDiff === 'true') {
    const diff = patches.map(patch => `\`\`\`diff\n${patch}\n\`\`\``).join('\n\n')

    data.body += `<details><summary>Show Diff</summary>

${diff}
</details>
`
  }

  const commentMaximumLength = 65536

  if (data.body.length > commentMaximumLength) {
    data.body = `${data.header}
##### Plan: \`${summary.create}\` to add, \`${summary.update}\` to change, \`${summary.delete}\` to destroy
##### Warning: The generated comment is too long, check [the output](https://github.com/${repo.owner}/${repo.repo}/actions/runs/${runId}) for the full detail.
${data.footer}`
  }
}
