import github from '@actions/github'

export default function (data) {
  // extract relevant variables
  const { diff: { summary, patches }, textContent, customHeader } = data
  const { runId, sha } = github.context
  const repo = data.repo
  const owner = data.owner

  const headerText = customHeader || ':robot: *Terraform Report*'

  data.header = headerText
  data.footer = `This comment was generated by [Terraform Pull Request Report Generator](https://github.com/ahmadnassri/action-terraform-report) - action run [\`#${runId}\`](https://github.com/${owner}/${github.context.repo.owner}//${github.context.repo.owner}/actions/runs/${runId}) - commit ${sha}`

  data.body = `
### ${data.header}
---
##### Plan: \`${summary.create}\` to add, \`${summary.update}\` to change, \`${summary.delete}\` to destroy
`

  if (data.showPlan === 'true') {
    data.body += `
<details><summary>Show Plan</summary>

\`\`\`terraform
${textContent}
\`\`\`
</details>

`
  }

  if (data.showDiff === 'true') {
    const diff = patches.map(patch => `\`\`\`diff\n${patch}\n\`\`\``).join('\n\n')

    data.body += `<details><summary>Show Diff</summary>

${diff}
</details>
`
  }

  data.body += `
---
> ${data.footer}
`
}
